#!/usr/bin/env python3
"""Static generator for *The Long Way from Light to JPEG*.

Chapters are Markdown fragments in _src/<id>.md. This script:

  * expands directives before Markdown conversion:
      {{include <file>::<name>}}   source of one function/class from
                                   code/<file>, extracted via ast, so
                                   listings are the tested code itself
      {{listing <file>}}           a whole file from code/
      {{figure <id> | <caption>}}  numbered figure from assets/figures/
      {{fig <id>}}                 "Figure P.N" cross-reference link
  * converts Markdown (tables, fenced code + Pygments, admonitions,
    smart typography), wraps section numbers in .secno spans,
  * wraps each page in the shared chrome: header, opener, prev/next
    navigation, MathJax, copy buttons.

Figures are never computed here — code/make_figures.py owns that.
The build fails if a referenced figure file is missing.
"""

import ast
import html
import os
import re
import subprocess
import sys

import markdown

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "_src")
CODE = os.path.join(HERE, "code")
FIGS = os.path.join(HERE, "assets", "figures")

BOOK_TITLE = "The Long Way from Light to JPEG"
BOOK_SUB = ("A plain-language, code-first tour of the RAW-to-JPEG "
            "pipeline — from photon to pixel.")

# (id, eyebrow, number-label for TOC/figures, title, one-line description)
PAGES = [
    ("setup", "Chapter 0", "0", "Setup",
     "Why this book, the toolkit, and the contract every line of code in it obeys."),
    ("camera", "Chapter 1", "1", "The Simulated Camera System",
     "Scenes as spectra, fictional lenses, a noisy sensor — ground truth for the whole book."),
    ("photons", "Chapter 2", "2", "From Photons to a Bayer Array",
     "Exposure, noise, black level, and why the sensor sees a mosaic instead of a picture."),
    ("white-balance", "Chapter 3", "3", "White Balance Comes First",
     "Undoing the illuminant on the raw mosaic — and proving the pipeline's order matters."),
    ("demosaicing", "Chapter 4", "4", "Demosaicing",
     "From one value per pixel to three: bilinear, edge-aware, and AHD, measured against truth."),
    ("color", "Chapter 5", "5", "Getting the Color Right",
     "Camera RGB is not a color space; the matrix that maps it toward one, derived from spectral ground truth."),
    ("lens", "Chapter 6", "6", "Undoing the Lens",
     "Vignetting, chromatic aberration, and distortion, inverted from known coefficients."),
    ("tone", "Chapter 7", "7", "Tone",
     "Gamma, curves, highlight reconstruction, and local tone mapping."),
    ("detail", "Chapter 8", "8", "Detail and Noise",
     "Sharpening and noise reduction, from unsharp mask to Non-Local Means."),
    ("encoding", "Chapter 9", "9", "Output Encoding",
     "Resampling, chroma subsampling, and a from-scratch JPEG encoder."),
    ("closing", "Chapter 10", "10", "Closing the Loop",
     "A real raw file through the reader's own pipeline — and why no two renderings agree."),
    ("appendix-api", "Appendix A", "A", "The pxp Package",
     "The simulated camera and pipeline as a standalone package — API reference."),
    ("appendix-glossary", "Appendix B", "B", "Glossary",
     "OECF, CFA, PSF, gamut, and the rest of the pipeline's vocabulary."),
    ("appendix-reading", "Appendix C", "C", "Further Reading",
     "Sources by pipeline stage — split into 'safe to reimplement' and 'read for understanding only'."),
]

# Header nav: label -> page id (only rendered once the page exists)
NAV = [
    ("Contents", "index"),
    ("Setup", "setup"),
    ("Camera", "camera"),
    ("Demosaic", "demosaicing"),
    ("Color", "color"),
    ("Tone", "tone"),
    ("JPEG", "encoding"),
]

COVER_META = """
<p><strong>Vijay Mathew</strong> — a companion book to
<a href="../../../lumen.html">Lumen</a>, the photo editor.</p>
<p>Every algorithm in plain, explicit code. Every figure generated by
the book's own code, against a simulated camera whose ground truth is
always known. Eleven chapters and three appendices — the whole way,
from photon to JPEG.</p>
"""

MATHJAX = """
<script>
window.MathJax = {
  tex: { inlineMath: [['\\\\(','\\\\)']], displayMath: [['\\\\[','\\\\]']] },
  options: { skipHtmlTags: ['script','noscript','style','textarea','pre','code'] }
};
</script>
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js" id="MathJax-script" async></script>
"""

COPY_JS = """
<script>
document.querySelectorAll('.prose .highlight').forEach(function (block) {
  block.classList.add('codeblock');
  var pre = block.querySelector('pre');
  if (!pre) return;
  var btn = document.createElement('button');
  btn.className = 'copy-btn'; btn.textContent = 'Copy';
  btn.addEventListener('click', function () {
    navigator.clipboard.writeText(pre.innerText).then(function () {
      btn.textContent = 'Copied'; setTimeout(function () { btn.textContent = 'Copy'; }, 1400);
    });
  });
  block.appendChild(btn);
});
</script>
"""

HEAD = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} — {book}</title>
<meta name="description" content="{desc}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,500;0,600;1,400;1,500&family=JetBrains+Mono:wght@400;500&family=Outfit:wght@300;400;500;600&display=swap" rel="stylesheet">
<link rel="stylesheet" href="theme.css">
{mathjax}
</head>
<body>
<header class="site-header"><div class="site-header-inner">
<a class="book-title" href="index.html">{book}</a>
<nav class="book-nav">{nav}</nav>
</div></header>
"""

FOOT = """{copy}
</body>
</html>
"""

MD_EXTENSIONS = ["tables", "fenced_code", "codehilite", "admonition", "smarty"]
MD_CONFIG = {"codehilite": {"css_class": "highlight", "guess_lang": False}}


def fail(msg):
    sys.exit(f"build.py: error: {msg}")


DRAFT_MARK = "<!-- draft -->"


def run_tests():
    """The book does not build on broken code.

    Chapter 0 tells the reader the two-tier tests run on every build of
    the book; this is where that sentence is made true.
    """
    result = subprocess.run(
        [sys.executable, "-m", "unittest", "discover", "-s", "tests"],
        cwd=CODE, capture_output=True, text=True)
    status = result.stderr.strip().splitlines()[-1] if result.stderr else ""
    if result.returncode != 0:
        sys.stderr.write(result.stderr)
        fail("code tests failed — fix code/ before building the book")
    if "skipped" in status:
        print(f"tests: {status} — WARNING: skipped tests mean the "
              f"two-tier contract is not fully enforced (NumPy missing?)")
    else:
        print(f"tests: {status}")


MATH = re.compile(r"\\\(.+?\\\)|\\\[.+?\\\]", re.S)


def stash_math(text):
    """Hide MathJax spans from Markdown, which eats \\( and \\[.

    Runs on the raw chapter source, before directives inject code, so
    listings are never scanned for math.
    """
    stash = []

    def keep(m):
        stash.append(m.group(0))
        return f"MATHSTASH{len(stash) - 1}ENDMATH"

    return MATH.sub(keep, text), stash


def restore_math(body, stash):
    return re.sub(
        r"MATHSTASH(\d+)ENDMATH",
        lambda m: html.escape(stash[int(m.group(1))], quote=False),
        body)


def extract_source(relpath, name):
    """The source lines of one top-level def/class in code/<relpath>."""
    path = os.path.join(CODE, relpath)
    if not os.path.exists(path):
        fail(f"include: no such file: code/{relpath}")
    with open(path) as f:
        source = f.read()
    for node in ast.parse(source).body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef,
                             ast.ClassDef)) and node.name == name:
            start = node.lineno
            if node.decorator_list:
                start = min(d.lineno for d in node.decorator_list)
            lines = source.splitlines()[start - 1:node.end_lineno]
            return "\n".join(lines)
    fail(f"include: no def/class named {name!r} in code/{relpath}")


def listing_block(relpath, code):
    provenance = (f'<div class="listing-src">from '
                  f'<code>code/{html.escape(relpath)}</code></div>')
    return f"{provenance}\n\n```python\n{code}\n```\n"


def caption_html(text):
    """Markdown for figure captions, unwrapped from its <p>."""
    rendered = markdown.markdown(text.strip(), extensions=["smarty"])
    return re.sub(r"^<p>|</p>$", "", rendered.strip())


def scan_figures():
    """Pass 1: number every figure across the book.

    Returns {figure_id: (page_href, label)} where label is 'P.N' from
    the page's number-label and the figure's order within its page.
    """
    registry = {}
    for pid, _, numlabel, _, _ in PAGES:
        frag = os.path.join(SRC, pid + ".md")
        if not os.path.exists(frag):
            continue
        with open(frag) as f:
            text = f.read()
        for n, m in enumerate(
                re.finditer(r"\{\{figure\s+([\w-]+)\s*\|", text), start=1):
            fig_id = m.group(1)
            if fig_id in registry:
                fail(f"duplicate figure id {fig_id!r} ({pid})")
            registry[fig_id] = (pid + ".html", f"{numlabel}.{n}")
    return registry


def expand_directives(text, page_href, figures):
    def do_include(m):
        relpath, name = m.group(1).strip(), m.group(2).strip()
        return listing_block(relpath, extract_source(relpath, name))

    def do_listing(m):
        relpath = m.group(1).strip()
        path = os.path.join(CODE, relpath)
        if not os.path.exists(path):
            fail(f"listing: no such file: code/{relpath}")
        with open(path) as f:
            return listing_block(relpath, f.read().rstrip())

    def do_figure(m):
        fig_id, caption = m.group(1), m.group(2).strip()
        png = os.path.join(FIGS, fig_id + ".png")
        if not os.path.exists(png):
            fail(f"figure {fig_id!r}: assets/figures/{fig_id}.png missing "
                 f"— run code/make_figures.py")
        label = figures[fig_id][1]
        return (f'<figure id="fig-{fig_id}">\n'
                f'<img src="assets/figures/{fig_id}.png" '
                f'alt="Figure {label}">\n'
                f'<figcaption><span class="figno">Figure {label}</span> '
                f'{caption_html(caption)}</figcaption>\n</figure>\n')

    def do_ref(m):
        fig_id = m.group(1)
        if fig_id not in figures:
            fail(f"fig reference to unknown figure {fig_id!r}")
        href, label = figures[fig_id]
        anchor = f"#fig-{fig_id}"
        target = anchor if href == page_href else href + anchor
        return f'<a href="{target}">Figure {label}</a>'

    text = re.sub(r"\{\{include\s+([^:}]+)::([^}]+)\}\}", do_include, text)
    text = re.sub(r"\{\{listing\s+([^}]+)\}\}", do_listing, text)
    text = re.sub(r"\{\{figure\s+([\w-]+)\s*\|\s*(.*?)\}\}",
                  do_figure, text, flags=re.S)
    text = re.sub(r"\{\{fig\s+([\w-]+)\}\}", do_ref, text)
    leftover = re.search(r"\{\{[^}]*\}\}", text)
    if leftover:
        fail(f"unrecognized directive: {leftover.group(0)[:60]}")
    return text


def number_headings(body):
    """Wrap leading '0.1' / 'A.2' section numbers in .secno spans."""
    return re.sub(
        r"<h([23])>((?:\d+|[A-Z])\.\d+)\s+",
        lambda m: (f'<h{m.group(1)} id="sec-{m.group(2).replace(".", "-")}">'
                   f'<span class="secno">{m.group(2)}</span>'),
        body)


def nav_html(active_href, built):
    out = []
    for label, pid in NAV:
        href = pid + ".html"
        if pid != "index" and pid not in built:
            continue
        cls = ' class="active"' if href == active_href else ""
        out.append(f'<a href="{href}"{cls}>{label}</a>')
    return "".join(out)


def chapter_nav(i, built):
    def link(kind, page):
        pid, eyebrow, _, title, _ = page
        return (f'<div class="{kind}"><a href="{pid}.html">'
                f'<span class="label">{"&larr; " if kind == "prev" else ""}'
                f'{html.escape(eyebrow)}'
                f'{" &rarr;" if kind == "next" else ""}</span>'
                f'<span class="ttl">{html.escape(title)}</span></a></div>')

    prev_html = ('<div class="prev"><a href="index.html">'
                 '<span class="label">&larr; Contents</span>'
                 f'<span class="ttl">{BOOK_TITLE}</span></a></div>')
    for j in range(i - 1, -1, -1):
        if PAGES[j][0] in built:
            prev_html = link("prev", PAGES[j])
            break
    next_html = '<div class="next"></div>'
    for j in range(i + 1, len(PAGES)):
        if PAGES[j][0] in built:
            next_html = link("next", PAGES[j])
            break
    return f'<nav class="chapter-nav">{prev_html}{next_html}</nav>'


def render_chapter(i, figures, built):
    pid, eyebrow, _, title, desc = PAGES[i]
    href = pid + ".html"
    with open(os.path.join(SRC, pid + ".md")) as f:
        text = f.read()

    draft = text.lstrip().startswith(DRAFT_MARK)
    if draft:
        text = text.lstrip()[len(DRAFT_MARK):]
        eyebrow_html = (f'{html.escape(eyebrow)}'
                        f'<span class="draft-chip">Draft</span>')
    else:
        eyebrow_html = html.escape(eyebrow)

    text, math = stash_math(text)
    text = expand_directives(text, href, figures)
    md = markdown.Markdown(extensions=MD_EXTENSIONS,
                           extension_configs=MD_CONFIG)
    body = restore_math(number_headings(md.convert(text)), math)

    opener = (f'<div class="opener">\n'
              f'<span class="opener-label">{eyebrow_html}</span>\n'
              f'<h1 class="opener-title">{html.escape(title)}</h1>\n'
              f'<p class="opener-lede">{html.escape(desc)}</p>\n'
              f'</div>\n')
    head = HEAD.format(title=html.escape(title), book=BOOK_TITLE,
                       desc=html.escape(desc), mathjax=MATHJAX,
                       nav=nav_html(href, built))
    page = (f'<main class="page">\n{opener}'
            f'<article class="prose">\n{body}\n</article>\n'
            f'{chapter_nav(i, built)}\n</main>\n')
    with open(os.path.join(HERE, href), "w") as f:
        f.write(head + page + FOOT.format(copy=COPY_JS))
    return href


def render_cover(built):
    entries = []
    for pid, _, numlabel, title, desc in PAGES:
        if pid in built:
            chip = ('<span class="soon">draft</span>'
                    if built[pid] else "")
            body = (f'<a href="{pid}.html">{html.escape(title)}{chip}'
                    f'<span class="desc">{html.escape(desc)}</span></a>')
        else:
            body = (f'<span class="pending">{html.escape(title)}'
                    f'<span class="soon">in preparation</span>'
                    f'<span class="desc">{html.escape(desc)}</span></span>')
        entries.append(f'<li class="toc-entry"><span class="tn">{numlabel}'
                       f'</span>{body}</li>')
    toc = '<ol class="toc-list">\n' + "\n".join(entries) + "\n</ol>"

    head = HEAD.format(title="Contents", book=BOOK_TITLE,
                       desc=BOOK_SUB, mathjax="",
                       nav=nav_html("index.html", built))
    page = (f'<main class="cover">\n'
            f'<div class="cover-eyebrow">From Photon to Pixel</div>\n'
            f'<h1 class="cover-title">The Long Way from Light '
            f'to JPEG</h1>\n'
            f'<p class="cover-sub">{html.escape(BOOK_SUB)}</p>\n'
            f'<div class="cover-rule"></div>\n'
            f'<div class="cover-meta">{COVER_META}</div>\n'
            f'{toc}\n</main>\n')
    with open(os.path.join(HERE, "index.html"), "w") as f:
        f.write(head + page + FOOT.format(copy=""))
    return "index.html"


def main():
    run_tests()
    built = {}
    for pid, *_ in PAGES:
        frag = os.path.join(SRC, pid + ".md")
        if os.path.exists(frag):
            with open(frag) as f:
                built[pid] = f.read().lstrip().startswith(DRAFT_MARK)
    figures = scan_figures()
    out = [render_cover(built)]
    for i, page in enumerate(PAGES):
        if page[0] in built:
            out.append(render_chapter(i, figures, built))
    pending = len(PAGES) - len(built)
    print(f"Built: {', '.join(out)}  ({pending} page(s) pending)")


if __name__ == "__main__":
    main()
