project:
  type: book
  output-dir: html

book:
  title: "Using Unix Command Line Tools to Supercharge Your Development Workflow"
  author: "Vijay Mathew"
  date: today
  date-format: "MMMM D, YYYY"
  chapters:
    - index.md
    - introduction.md
    - chapter_1.md
    - chapter_2.md
    - chapter_3.md
    - chapter_4.md
    - chapter_5.md
    - chapter_6.md
    - chapter_7.md
    - chapter_8.md
    - chapter_9.md
    - chapter_10.md
    - chapter_11.md
    - chapter_12.md
    - bibliography.md

format:
  html:
    theme:
      light: [cosmo, nex-book.scss]
      dark: [darkly, nex-book.scss]
    toc: true
    toc-depth: 3
    number-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    css: styles.css
    code-copy: true
    code-overflow: wrap
    include-after-body: includes/adjust-chapter-numbers.html
  pdf:
    output-file: cli-workflow-guide.pdf
    pdf-engine: pdflatex
    documentclass: scrbook
    number-sections: true
    toc: true
    toc-depth: 2

crossref:
  chapters: true

execute:
  freeze: auto
