#!/usr/bin/env python3
"""Static site generator for the Nex blog.

A post is one Markdown file in ``posts/``, named ``YYYY-MM-DD-slug.md``:

    ---
    title: Handling command-line arguments in Nex
    tags: [how-to, cli]
    summary: One or two sentences for the index, the feed and link previews.
    ---

    The body, in Markdown. Fenced code blocks are highlighted as Nex unless
    they name another language or start with "$ ".

Optional front matter: ``date`` (overrides the one in the file name),
``updated``, ``slug``, and ``draft: true`` (built only with ``--drafts``).

Running the script writes, next to it, ``<slug>.html`` for every post,
``index.html`` (newest first, by year), ``tags/`` (a page per tag and an
overview) and ``feed.xml`` (Atom). All of that is build output: it is
git-ignored and regenerated by .github/workflows/pages.yml on every push.

    pip install -r requirements.txt
    python3 build.py [--drafts]
"""
import datetime, glob, html, os, re, shutil, sys
from urllib.parse import quote

import markdown, yaml

HERE  = os.path.dirname(os.path.abspath(__file__))
POSTS = os.path.join(HERE, "posts")

SITE_URL   = "https://schemer.in"
BLOG_URL   = SITE_URL + "/nex/blog/"
BLOG_TITLE = "The Nex Blog"
BLOG_DESC  = "Notes on Nex: how to use it, how it is designed, and what is changing."
AUTHOR     = "Vijay Mathew"
REPO       = "vijaymathew/nex"

# Comments are GitHub Discussions threads, embedded by giscus (https://giscus.app).
# Install the giscus app on REPO, then set "enabled" to True. Until then each
# post ends with a plain link that starts a discussion.
GISCUS = {
    "enabled":     False,
    "repo_id":     "R_kgDORPL8hQ",
    "category":    "Announcements",
    "category_id": "DIC_kwDORPL8hc4DHU-f",
}

FRONT = re.compile(r"\A---\s*\n(.*?)\n---\s*\n(.*)\Z", re.S)
NAME  = re.compile(r"^(\d{4}-\d{2}-\d{2})-(.+)\.md$")
E = html.escape


def die(msg):
    sys.exit("blog: " + msg)


def as_date(value, where):
    if isinstance(value, datetime.datetime):
        return value.date()
    if isinstance(value, datetime.date):
        return value
    try:
        return datetime.date.fromisoformat(str(value))
    except ValueError:
        die(f"{where}: bad date {value!r}, expected YYYY-MM-DD")


def slugify(text):
    return re.sub(r"[^a-z0-9]+", "-", str(text).lower()).strip("-")


def load(fname):
    with open(os.path.join(POSTS, fname), encoding="utf-8") as f:
        m = FRONT.match(f.read())
    if not m:
        die(f"{fname}: no front matter (a '---' block at the top of the file)")
    try:
        meta = yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError as e:
        die(f"{fname}: front matter is not valid YAML: {e}")
    named = NAME.match(fname)
    if not meta.get("title"):
        die(f"{fname}: front matter needs a title")
    if not (named or meta.get("date")):
        die(f"{fname}: name the file YYYY-MM-DD-slug.md, or give it a date")
    date = as_date(meta.get("date") or named.group(1), fname)
    tags = meta.get("tags") or []
    if isinstance(tags, str):
        tags = [t.strip() for t in tags.split(",")]
    md = markdown.Markdown(
        extensions=["fenced_code", "tables", "footnotes", "attr_list", "toc", "smarty"],
        # "--" is a Nex comment and a command-line flag; never turn it into a dash.
        extension_configs={"smarty": {"smart_dashes": False}})
    body = md.convert(m.group(2))
    words = len(re.sub(r"<[^>]+>", " ", body).split())
    return {
        "title":   str(meta["title"]),
        "date":    date,
        "updated": as_date(meta["updated"], fname) if meta.get("updated") else date,
        "slug":    slugify(meta.get("slug") or (named.group(2) if named else meta["title"])),
        "tags":    [str(t) for t in tags if str(t).strip()],
        "summary": str(meta.get("summary") or "").strip(),
        "draft":   bool(meta.get("draft")),
        "minutes": max(1, round(words / 220)),
        "body":    body,
        "source":  fname,
    }


# ── page chrome ──────────────────────────────────────────────────────────────

def page(*, root, title, desc, url, body, head=""):
    """Wrap ``body`` in the site chrome. ``root`` is the relative path from the
    page to the ``nex/`` directory ("../" for blog pages, "../../" for tags)."""
    logo = f"{root}assets/logo/nex-logo-concept-7-orbit-n"
    return f"""<!DOCTYPE html>
<html lang="en" data-theme="light">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{E(title)}</title>
  <meta name="description" content="{E(desc)}">
  <link rel="canonical" href="{E(url)}">
  <meta property="og:site_name" content="Nex">
  <meta property="og:url" content="{E(url)}">
  <meta property="og:title" content="{E(title)}">
  <meta property="og:description" content="{E(desc)}">
  <meta property="og:image" content="{SITE_URL}/nex/assets/social-card.png">
  <meta name="twitter:card" content="summary_large_image">
{head}  <link rel="alternate" type="application/atom+xml" title="{E(BLOG_TITLE)}" href="{BLOG_URL}feed.xml">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{root}site.css">
  <script src="{root}site.js"></script>
  <link rel="icon" href="{root}assets/icons/nex.svg" type="image/svg+xml">
  <link rel="icon" href="{root}assets/icons/nex-32.png" type="image/png" sizes="32x32">
  <link rel="apple-touch-icon" href="{root}assets/icons/nex-180.png">
</head>
<body>

<nav class="nav">
  <div class="wrap">
    <a class="brand" href="{root}../nex.html"><img src="{logo}-light.svg" data-light="{logo}-light.svg" data-dark="{logo}-dark.svg" alt="">nex</a>
    <div class="nav-links">
      <a href="{root}tutorial.html">Tutorial</a>
      <a href="{root}syntax.html">Syntax</a>
      <a href="{root}../nex.html#learn">Learn</a>
      <a href="{root}../nex.html#install">Install</a>
      <a href="{root}blog/index.html">Blog</a>
      <a class="gh" href="https://github.com/{REPO}" target="_blank" rel="noopener">GitHub ↗</a>
    </div>
    <button class="toggle" id="theme" aria-label="Toggle dark mode" title="Toggle theme">🌙</button>
  </div>
</nav>

<div class="wrap narrow">
{body}
</div>

<footer>
  <div class="wrap">
    <span class="mono">nex</span>
    <a href="https://github.com/{REPO}">GitHub</a>
    <a href="{root}tutorial.html">Tutorial</a>
    <a href="{root}syntax.html">Syntax</a>
    <a href="{root}blog/index.html">Blog</a>
    <a href="{root}blog/feed.xml">Feed</a>
    <span class="r">by <a href="{root}../index.html">{E(AUTHOR)}</a></span>
  </div>
</footer>

</body>
</html>
"""


def chips(tags, blog, counts=None):
    """Tag links. ``blog`` is the relative path from the page to the blog."""
    if not tags:
        return ""
    return '<span class="chips">' + "".join(
        f'<a class="chip" href="{blog}tags/{slugify(t)}.html">{E(t)}'
        + (f" <i>{counts[t]}</i>" if counts else "") + "</a>"
        for t in tags) + "</span>"


def post_item(p, blog, date_format="%-d %b"):
    summary = f"\n      <p>{E(p['summary'])}</p>" if p["summary"] else ""
    return f"""  <article class="post-item">
    <time datetime="{p['date'].isoformat()}">{p['date'].strftime(date_format)}</time>
    <div>
      <h3><a href="{blog}{p['slug']}.html">{E(p['title'])}</a></h3>{summary}
      {chips(p['tags'], blog)}
    </div>
  </article>
"""


def comments(p):
    if GISCUS["enabled"]:
        return f"""  <section class="comments" id="comments">
    <h2>Comments</h2>
    <div class="giscus" data-repo="{REPO}" data-repo-id="{GISCUS['repo_id']}" data-category="{E(GISCUS['category'])}" data-category-id="{GISCUS['category_id']}" data-mapping="pathname" data-strict="1" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-lang="en" data-loading="lazy"></div>
    <noscript><p>Comments are on <a href="https://github.com/{REPO}/discussions">GitHub Discussions</a>.</p></noscript>
  </section>
"""
    new = f"https://github.com/{REPO}/discussions/new?category=general&title={quote(p['title'])}"
    return f"""  <section class="comments" id="comments">
    <h2>Comments</h2>
    <p>Questions, corrections, a better way to do it? <a href="{new}" target="_blank" rel="noopener">Start a discussion on GitHub →</a></p>
  </section>
"""


# ── pages ────────────────────────────────────────────────────────────────────

def post_page(p, newer, older):
    head = (f'  <meta property="og:type" content="article">\n'
            f'  <meta property="article:published_time" content="{p["date"].isoformat()}">\n'
            + "".join(f'  <meta property="article:tag" content="{E(t)}">\n' for t in p["tags"]))
    lead = f'\n    <p class="lead">{E(p["summary"])}</p>' if p["summary"] else ""
    cards = "".join(
        f'    <a class="next-card" href="./{q["slug"]}.html"><small>{label}</small><b>{E(q["title"])}</b>'
        f'<span>{q["date"].strftime("%-d %B %Y")}</span></a>\n'
        for label, q in (("newer", newer), ("older", older)) if q)
    cards += '    <a class="next-card" href="./index.html"><small>blog</small><b>All posts</b><span>Everything, newest first.</span></a>\n'
    body = f"""  <header class="page-head post-head">
    <span class="eyebrow">// blog</span>
    <h1>{E(p['title'])}</h1>{lead}
    <p class="post-meta"><time datetime="{p['date'].isoformat()}">{p['date'].strftime("%-d %B %Y")}</time><span>{p['minutes']} min read</span>{chips(p['tags'], "./")}</p>
  </header>

  <article class="article prose post">
{p['body']}
  </article>

  <div class="post-foot">
  <div class="next-cards">
    <h2>Keep reading</h2>
{cards}  </div>
{comments(p)}  </div>"""
    return page(root="../", title=f"{p['title']} — Nex", desc=p["summary"] or BLOG_DESC,
                url=f"{BLOG_URL}{p['slug']}.html", body=body, head=head)


def index_page(posts, counts):
    out, year = "", None
    for p in posts:
        if p["date"].year != year:
            year = p["date"].year
            out += f'  <h2 class="year-h">{year}</h2>\n'
        out += post_item(p, "./")
    if not posts:
        out = '  <p class="blurb">Nothing here yet.</p>\n'
    tags = sorted(counts, key=lambda t: (-counts[t], t.lower()))
    bar = (f'  <p class="tag-bar">{chips(tags, "./", counts)}<a class="more" href="./tags/index.html">All tags →</a></p>\n'
           if tags else "")
    body = f"""  <header class="page-head">
    <span class="eyebrow">// blog</span>
    <h1>{E(BLOG_TITLE)}</h1>
    <p class="lead">{E(BLOG_DESC)} <a href="./feed.xml">Subscribe to the feed</a>.</p>
  </header>

  <div class="posts">
{bar}{out}  </div>"""
    return page(root="../", title=f"{BLOG_TITLE}", desc=BLOG_DESC, url=BLOG_URL, body=body,
                head='  <meta property="og:type" content="website">\n')


def tag_page(tag, posts):
    n = len(posts)
    body = f"""  <header class="page-head">
    <span class="eyebrow">// tag</span>
    <h1>{E(tag)}</h1>
    <p class="lead">{n} post{"" if n == 1 else "s"}, newest first. <a href="./index.html">All tags</a> · <a href="../index.html">All posts</a></p>
  </header>

  <div class="posts">
{"".join(post_item(p, "../", "%-d %b %Y") for p in posts)}  </div>"""
    return page(root="../../", title=f"Posts tagged {tag} — Nex", desc=f"Nex blog posts tagged {tag}.",
                url=f"{BLOG_URL}tags/{slugify(tag)}.html", body=body)


def tags_page(by_tag):
    out = ""
    for tag in sorted(by_tag, key=str.lower):
        rows = "".join(
            f'    <li><time datetime="{p["date"].isoformat()}">{p["date"].strftime("%-d %b %Y")}</time>'
            f'<a href="../{p["slug"]}.html">{E(p["title"])}</a></li>\n' for p in by_tag[tag])
        out += (f'  <h2 class="year-h" id="{slugify(tag)}"><a href="./{slugify(tag)}.html">{E(tag)}</a>'
                f' <i>{len(by_tag[tag])}</i></h2>\n  <ul class="tag-posts">\n{rows}  </ul>\n')
    body = f"""  <header class="page-head">
    <span class="eyebrow">// blog</span>
    <h1>Tags</h1>
    <p class="lead">Every post, grouped by tag. <a href="../index.html">All posts by date</a></p>
  </header>

  <div class="posts">
{out}  </div>"""
    return page(root="../../", title="Tags — The Nex Blog", desc="Nex blog posts grouped by tag.",
                url=f"{BLOG_URL}tags/", body=body)


def feed(posts):
    stamp = lambda d: d.isoformat() + "T00:00:00Z"
    entries = "".join(f"""  <entry>
    <title>{E(p['title'])}</title>
    <link href="{BLOG_URL}{p['slug']}.html"/>
    <id>{BLOG_URL}{p['slug']}.html</id>
    <published>{stamp(p['date'])}</published>
    <updated>{stamp(p['updated'])}</updated>
    <summary>{E(p['summary'])}</summary>
{"".join(f'    <category term="{E(t)}"/>' + chr(10) for t in p['tags'])}    <content type="html" xml:base="{BLOG_URL}">{E(p['body'])}</content>
  </entry>
""" for p in posts[:20])
    updated = stamp(max((p["updated"] for p in posts), default=datetime.date(2026, 1, 1)))
    return f"""<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>{E(BLOG_TITLE)}</title>
  <subtitle>{E(BLOG_DESC)}</subtitle>
  <link href="{BLOG_URL}feed.xml" rel="self"/>
  <link href="{BLOG_URL}"/>
  <id>{BLOG_URL}</id>
  <updated>{updated}</updated>
  <author><name>{E(AUTHOR)}</name></author>
{entries}</feed>
"""


def write(rel, text):
    path = os.path.join(HERE, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)


def main():
    drafts = "--drafts" in sys.argv[1:]
    posts = [load(f) for f in sorted(os.listdir(POSTS)) if f.endswith(".md")]
    posts = [p for p in posts if drafts or not p["draft"]]
    posts.sort(key=lambda p: (p["date"], p["slug"]), reverse=True)

    seen = {"index": "the blog index"}
    for p in posts:
        if p["slug"] in seen:
            die(f"{p['source']}: slug '{p['slug']}' is already used by {seen[p['slug']]}")
        seen[p["slug"]] = p["source"]

    by_tag, names = {}, {}
    for p in posts:
        # Tags that differ only in case or punctuation are one tag.
        p["tags"] = list(dict.fromkeys(names.setdefault(slugify(t), t) for t in p["tags"] if slugify(t)))
        for t in p["tags"]:
            by_tag.setdefault(t, []).append(p)
    if "index" in names:
        die("'index' cannot be used as a tag")
    counts = {t: len(ps) for t, ps in by_tag.items()}

    # Clear the previous build, so a renamed or deleted post leaves nothing behind.
    for old in glob.glob(os.path.join(HERE, "*.html")):
        os.remove(old)
    shutil.rmtree(os.path.join(HERE, "tags"), ignore_errors=True)

    for i, p in enumerate(posts):
        newer = posts[i - 1] if i > 0 else None
        older = posts[i + 1] if i + 1 < len(posts) else None
        write(p["slug"] + ".html", post_page(p, newer, older))
    write("index.html", index_page(posts, counts))
    write("tags/index.html", tags_page(by_tag))
    for tag, tagged in by_tag.items():
        write(f"tags/{slugify(tag)}.html", tag_page(tag, tagged))
    write("feed.xml", feed(posts))
    print(f"blog: {len(posts)} post(s), {len(by_tag)} tag(s)")


if __name__ == "__main__":
    main()
